### ISSUE TITLE
insane memory consumption jump during evaluation when using contact force API

### ISSUE THREAD

**Issue by kwang-12** [haosulab/ManiSkill#1070]
Hello.
I am observing ridiculous memory usage during evaluation which causes sim to stop.
1. Hardware:
nvidia H100 80GB HBM3 with xeon plat 8480+ and 225 GB.
2. code:
simplified unitree go2 env with custom reward functions.
3. nvidia driver versions:
NVIDIA-SMI 570.133.07             Driver Version: 570.133.07     CUDA Version: 12.8 
4. error message:
Epoch: 61, global_step=49152000
Evaluating
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/test_mskill/ppo.py", line 287, in <module>
    eval_obs, eval_rew, eval_terminations, eval_truncations, eval_infos = eval_envs.step(agent.get_action(eval_obs, deterministic=True))
  File "/opt/conda/lib/python3.9/site-packages/mani_skill/vector/wrappers/gymnasium.py", line 148, in step
    obs, infos = self.reset(options=dict(env_idx=env_idx))
  File "/opt/conda/lib/python3.9/site-packages/mani_skill/vector/wrappers/gymnasium.py", line 93, in reset
    obs, info = self._env.reset(seed=seed, options=options)
  File "/opt/conda/lib/python3.9/site-packages/mani_skill/utils/wrappers/record.py", line 376, in reset
    obs, info = super().reset(*args, seed=seed, options=options, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/core.py", line 467, in reset
    return self.env.reset(seed=seed, options=options)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/core.py", line 467, in reset
    return self.env.reset(seed=seed, options=options)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/wrappers/order_enforcing.py", line 61, in reset
    return self.env.reset(**kwargs)
  File "/opt/conda/lib/python3.9/site-packages/mani_skill/envs/sapien_env.py", line 874, in reset
    info = self.get_info()
  File "/opt/conda/lib/python3.9/site-packages/mani_skill/envs/sapien_env.py", line 1047, in get_info
    info.update(self.evaluate())
  File "/workspace/test_mskill/envs/env_flat.py", line 237, in evaluate
    ret = super().evaluate()
  File "/workspace/test_mskill/envs/env_flat.py", line 83, in evaluate
    is_fallen = self.agent.is_fallen()
  File "/workspace/test_mskill/agents/go2.py", line 75, in is_fallen
    forces = self.robot.get_net_contact_forces(["base",
  File "/opt/conda/lib/python3.9/site-packages/mani_skill/utils/structs/articulation.py", line 427, in get_net_contact_forces
    return self.get_net_contact_impulses(link_names) / self.scene.timestep
  File "/opt/conda/lib/python3.9/site-packages/mani_skill/utils/structs/articulation.py", line 388, in get_net_contact_impulses
    query.cuda_impulses.torch()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/test_mskill/ppo.py", line 287, in <module>
    eval_obs, eval_rew, eval_terminations, eval_truncations, eval_infos = eval_envs.step(agent.get_action(eval_obs, deterministic=True))
  File "/opt/conda/lib/python3.9/site-packages/mani_skill/vector/wrappers/gymnasium.py", line 148, in step
    obs, infos = self.reset(options=dict(env_idx=env_idx))
  File "/opt/conda/lib/python3.9/site-packages/mani_skill/vector/wrappers/gymnasium.py", line 93, in reset
    obs, info = self._env.reset(seed=seed, options=options)
  File "/opt/conda/lib/python3.9/site-packages/mani_skill/utils/wrappers/record.py", line 376, in reset
    obs, info = super().reset(*args, seed=seed, options=options, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/core.py", line 467, in reset
    return self.env.reset(seed=seed, options=options)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/core.py", line 467, in reset
    return self.env.reset(seed=seed, options=options)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/wrappers/order_enforcing.py", line 61, in reset
    return self.env.reset(**kwargs)
  File "/opt/conda/lib/python3.9/site-packages/mani_skill/envs/sapien_env.py", line 874, in reset
    info = self.get_info()
  File "/opt/conda/lib/python3.9/site-packages/mani_skill/envs/sapien_env.py", line 1047, in get_info
    info.update(self.evaluate())
  File "/workspace/test_mskill/envs/env_flat.py", line 237, in evaluate
    ret = super().evaluate()
  File "/workspace/test_mskill/envs/env_flat.py", line 83, in evaluate
    is_fallen = self.agent.is_fallen()
  File "/workspace/test_mskill/agents/go2.py", line 75, in is_fallen
    forces = self.robot.get_net_contact_forces(["base",
  File "/opt/conda/lib/python3.9/site-packages/mani_skill/utils/structs/articulation.py", line 427, in get_net_contact_forces
    return self.get_net_contact_impulses(link_names) / self.scene.timestep
  File "/opt/conda/lib/python3.9/site-packages/mani_skill/utils/structs/articulation.py", line 388, in get_net_contact_impulses
    query.cuda_impulses.torch()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2025-05-16 04:47:26.676] [SAPIEN] [critical] /buildAgent/work/eb2f45c4acc808a0/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp
[2025-05-16 04:47:26.676] [SAPIEN] [critical] Mem free failed with error code 700!

[2025-05-16 04:47:26.676] [SAPIEN] [critical] /buildAgent/work/eb2f45c4acc808a0/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp
[2025-05-16 04:47:26.676] [SAPIEN] [critical] /buildAgent/work/eb2f45c4acc808a0/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp
[2025-05-16 04:47:26.676] [SAPIEN] [critical] /buildAgent/work/eb2f45c4acc808a0/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp
[2025-05-16 04:47:26.676] [SAPIEN] [critical] /buildAgent/work/eb2f45c4acc808a0/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp
[2025-05-16 04:47:26.677] [SAPIEN] [critical] /buildAgent/work/eb2f45c4acc808a0/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp
CUDA error at /__w/SAPIEN/SAPIEN/3rd_party/sapien-vulkan-2/src/core/buffer.cpp 103: an illegal memory access was encountered
scripts/run_flat_v2.sh: line 15:  3742 Segmentation fault      (core dumped) python3 -m test_mskill.ppo --env_id="go2-flat-reach-v2" --num_envs=4096 --update_epochs=8 --num_minibatches=32 --total_timesteps=204_800_000 --num_steps=200 --num_eval_steps=200 --gamma=0.99 --gae_lambda=0.95 --control_mode="pd_joint_delta_pos" --save_model --track

I'm also observing similar behavior on 4090. reducing num_eval_steps to 100 seems to somehow solve the problem but that just doesn't make sense to me (only 8 evaluation envs by default). Any help is appreciated.

**Comment by kwang-12** [comment]
Also worth mentioning that I have to reboot the pc once this error happens. Starting a new sim after the error will just result in simulation freezing with the script stuck at the initial evaluation.
nvidia-smi shows that the gpu is used by 100% but nothing actually happens:

Every 0.1s: nvidia-smi                                                       192-222-52-71: Fri May 16 05:03:34 2025

Fri May 16 05:03:34 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.133.07             Driver Version: 570.133.07     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          On  |   00000000:06:00.0 Off |                    0 |
| N/A   27C    P0            115W /  700W |    6205MiB /  81559MiB |    100%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A           75814    C+G   python3                                6164MiB |
+-----------------------------------------------------------------------------------------+


console output:
```
Running training
obs shape: (61,), act shape: (16,)
####
args.num_iterations=250 args.num_envs=4096 args.num_eval_envs=8
args.minibatch_size=25600 args.batch_size=819200 args.update_epochs=8
####
Epoch: 1, global_step=0
Evaluating
^C^C^C
```

**Comment by StoneT2000** [comment]
Using 100% of the GPU is normal and expected.

Do the other PPO baseline scripts work fine? Or is it just this task that is breaking.

**Comment by kwang-12** [comment]
Thank you for your reply!
I meant to say that I observed the VRAM usage jumped to 100% during evaluation.
This training session had 4096 simplified go2 envs. num_steps=200. 
The main script is `examples/baselines/ppo/ppo.py`
And the occurrence seems to be quite random. 
Have you ever encountered anything like this? What's the rough VRAM usage estimates for this training setup?


![Image](https://github.com/user-attachments/assets/b1f3ffdd-4186-485a-99d0-937ca4efdd28)

![Image](https://github.com/user-attachments/assets/06a53ac2-43b5-400f-b82d-c229f40ad691)

**Comment by StoneT2000** [comment]
First let's verify if it's just an environment problem or GPU issue with eg bad drivers

Are you able to run any of the other PPO baselines? eg run the PickCube training script in baselines.

Let it run for a long time and let me know about how the memory behaves

**Comment by kwang-12** [comment]
I did some testing using only the provided code from ManiSkill. 
Specifically, `ManiSkill/examples/baselines/ppo/ppo.py` and `AnymalC-Reach-v1`.

Running the baseline example with different numbers of training envs yielded same error behavior due to CUDA OOM errors.

Note that this error only happens if evaluation is enabled. Test runs completes without any problem if evaluation is disabled.

1. test run with 1024 training envs:
```
(base) root@5a9cae070a1f:/workspace#  cd /workspace ; /usr/bin/env /opt/conda/bin/python /root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 39365 -- /workspace/ManiSkill/examples/baselines/ppo/ppo.py --env_id AnymalC-Reach-v1 --seed 1 --num_envs 1024 --update_epochs 8 --num_minibatches 32 --gamma 0.99 --gae_lambda 0.95 --total_timesteps 50000000 --num-steps 16 --num-eval-steps 200 --num_eval_envs 16 --track 
2025-05-19 05:43:27,290 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
2025-05-19 05:43:28,441 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Saving eval videos to runs/AnymalC-Reach-v1__ppo__1__1747633403/videos
Running training
2025-05-19 05:43:31,604 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
####
args.num_iterations=3051 args.num_envs=1024 args.num_eval_envs=16
args.minibatch_size=512 args.batch_size=16384 args.update_epochs=8
####
Epoch: 1, global_step=0
Evaluating
2025-05-19 05:43:32,022 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
2025-05-19 05:43:38,808 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Evaluated 3200 steps resulting in 16 episodes
eval_success_once_mean=0.0
eval_fail_once_mean=0.0
eval_return_mean=64.66410827636719
eval_episode_len_mean=200.0
eval_reward_mean=0.32332056760787964
eval_success_at_end_mean=0.0
eval_fail_at_end_mean=0.0
model saved to runs/AnymalC-Reach-v1__ppo__1__1747633403/ckpt_1.pt
SPS: 1814
Epoch: 2, global_step=16384
SPS: 3184
Epoch: 3, global_step=32768
SPS: 4190
Epoch: 4, global_step=49152
SPS: 5087
Epoch: 5, global_step=65536
SPS: 5863
Epoch: 6, global_step=81920
SPS: 6405
Epoch: 7, global_step=98304
SPS: 6833
Epoch: 8, global_step=114688
SPS: 7220
Epoch: 9, global_step=131072
SPS: 7529
Epoch: 10, global_step=147456
SPS: 7815
Epoch: 11, global_step=163840
SPS: 8053
Epoch: 12, global_step=180224
SPS: 8277
Epoch: 13, global_step=196608
SPS: 8486
Epoch: 14, global_step=212992
SPS: 8656
Epoch: 15, global_step=229376
SPS: 8791
Epoch: 16, global_step=245760
SPS: 8920
Epoch: 17, global_step=262144
SPS: 9037
Epoch: 18, global_step=278528
SPS: 9151
Epoch: 19, global_step=294912
SPS: 9222
Epoch: 20, global_step=311296
SPS: 9299
Epoch: 21, global_step=327680
SPS: 9380
Epoch: 22, global_step=344064
SPS: 9451
Epoch: 23, global_step=360448
SPS: 9497
Epoch: 24, global_step=376832
SPS: 9563
Epoch: 25, global_step=393216
SPS: 9603
Epoch: 26, global_step=409600
Evaluating
2025-05-19 05:44:14,281 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
2025-05-19 05:44:20,233 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Backend tkagg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/workspace/ManiSkill/examples/baselines/ppo/ppo.py", line 283, in <module>
    eval_obs, eval_rew, eval_terminations, eval_truncations, eval_infos = eval_envs.step(agent.get_action(eval_obs, deterministic=True))
  File "/workspace/ManiSkill/mani_skill/vector/wrappers/gymnasium.py", line 148, in step
    obs, infos = self.reset(options=dict(env_idx=env_idx))
  File "/workspace/ManiSkill/mani_skill/vector/wrappers/gymnasium.py", line 93, in reset
    obs, info = self._env.reset(seed=seed, options=options)
  File "/workspace/ManiSkill/mani_skill/utils/wrappers/record.py", line 376, in reset
    obs, info = super().reset(*args, seed=seed, options=options, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/core.py", line 467, in reset
    return self.env.reset(seed=seed, options=options)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/core.py", line 467, in reset
    return self.env.reset(seed=seed, options=options)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/wrappers/order_enforcing.py", line 61, in reset
    return self.env.reset(**kwargs)
  File "/workspace/ManiSkill/mani_skill/envs/sapien_env.py", line 937, in reset
    info = self.get_info()
  File "/workspace/ManiSkill/mani_skill/envs/sapien_env.py", line 1118, in get_info
    info.update(self.evaluate())
  File "/workspace/ManiSkill/mani_skill/envs/tasks/quadruped/quadruped_reach.py", line 100, in evaluate
    is_fallen = self.agent.is_fallen()
  File "/workspace/ManiSkill/mani_skill/agents/robots/anymal/anymal_c.py", line 114, in is_fallen
    forces = self.robot.get_net_contact_forces(["base"])
  File "/workspace/ManiSkill/mani_skill/utils/structs/articulation.py", line 497, in get_net_contact_forces
    return self.get_net_contact_impulses(link_names) / self.scene.timestep
  File "/workspace/ManiSkill/mani_skill/utils/structs/articulation.py", line 456, in get_net_contact_impulses
    self.px.gpu_query_contact_body_impulses(query)
RuntimeError: CUDA error: out of memory
```


2. test run with 256 training envs:
```
(base) root@5a9cae070a1f:/workspace#  cd /workspace ; /usr/bin/env /opt/conda/bin/python /root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 58955 -- /workspace/ManiSkill/examples/baselines/ppo/ppo.py --env_id AnymalC-Reach-v1 --seed 1 --num_envs 256 --update_epochs 8 --num_minibatches 32 --gamma 0.99 --gae_lambda 0.95 --total_timesteps 50000000 --num-steps 16 --num-eval-steps 200 --num_eval_envs 16 --track 
2025-05-19 05:45:22,177 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
2025-05-19 05:45:22,773 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Saving eval videos to runs/AnymalC-Reach-v1__ppo__1__1747633520/videos
Running training
2025-05-19 05:45:25,789 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
####
args.num_iterations=12207 args.num_envs=256 args.num_eval_envs=16
args.minibatch_size=128 args.batch_size=4096 args.update_epochs=8
####
Epoch: 1, global_step=0
Evaluating
2025-05-19 05:45:26,216 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
2025-05-19 05:45:33,013 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Evaluated 3200 steps resulting in 16 episodes
eval_success_once_mean=0.0
eval_fail_once_mean=0.0
eval_return_mean=64.66410827636719
eval_episode_len_mean=200.0
eval_reward_mean=0.32332056760787964
eval_success_at_end_mean=0.0
eval_fail_at_end_mean=0.0
model saved to runs/AnymalC-Reach-v1__ppo__1__1747633520/ckpt_1.pt
SPS: 469
Epoch: 2, global_step=4096
SPS: 844
Epoch: 3, global_step=8192
SPS: 1160
Epoch: 4, global_step=12288
SPS: 1425
Epoch: 5, global_step=16384
SPS: 1644
Epoch: 6, global_step=20480
SPS: 1827
Epoch: 7, global_step=24576
SPS: 1993
Epoch: 8, global_step=28672
SPS: 2135
Epoch: 9, global_step=32768
SPS: 2262
Epoch: 10, global_step=36864
SPS: 2358
Epoch: 11, global_step=40960
SPS: 2402
Epoch: 12, global_step=45056
SPS: 2434
Epoch: 13, global_step=49152
SPS: 2461
Epoch: 14, global_step=53248
SPS: 2485
Epoch: 15, global_step=57344
SPS: 2509
Epoch: 16, global_step=61440
SPS: 2529
Epoch: 17, global_step=65536
SPS: 2547
Epoch: 18, global_step=69632
SPS: 2560
Epoch: 19, global_step=73728
SPS: 2568
Epoch: 20, global_step=77824
SPS: 2589
Epoch: 21, global_step=81920
SPS: 2608
Epoch: 22, global_step=86016
SPS: 2625
Epoch: 23, global_step=90112
SPS: 2637
Epoch: 24, global_step=94208
SPS: 2647
Epoch: 25, global_step=98304
SPS: 2651
Epoch: 26, global_step=102400
Evaluating
2025-05-19 05:46:04,440 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
2025-05-19 05:46:12,193 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Evaluated 3200 steps resulting in 16 episodes
eval_success_once_mean=0.0
eval_fail_once_mean=0.0
eval_return_mean=63.29351806640625
eval_episode_len_mean=200.0
eval_reward_mean=0.3164675831794739
eval_success_at_end_mean=0.0
eval_fail_at_end_mean=0.0
model saved to runs/AnymalC-Reach-v1__ppo__1__1747633520/ckpt_26.pt
SPS: 2208
Epoch: 27, global_step=106496
SPS: 2231
Epoch: 28, global_step=110592
SPS: 2251
Epoch: 29, global_step=114688
SPS: 2275
Epoch: 30, global_step=118784
SPS: 2292
Epoch: 31, global_step=122880
SPS: 2314
Epoch: 32, global_step=126976
SPS: 2337
Epoch: 33, global_step=131072
SPS: 2358
Epoch: 34, global_step=135168
SPS: 2378
Epoch: 35, global_step=139264
SPS: 2396
Epoch: 36, global_step=143360
SPS: 2414
Epoch: 37, global_step=147456
SPS: 2430
Epoch: 38, global_step=151552
SPS: 2447
Epoch: 39, global_step=155648
SPS: 2494
Epoch: 40, global_step=159744
SPS: 2521
Epoch: 41, global_step=163840
SPS: 2534
Epoch: 42, global_step=167936
SPS: 2543
Epoch: 43, global_step=172032
SPS: 2552
Epoch: 44, global_step=176128
SPS: 2561
Epoch: 45, global_step=180224
SPS: 2568
Epoch: 46, global_step=184320
SPS: 2584
Epoch: 47, global_step=188416
SPS: 2620
Epoch: 48, global_step=192512
SPS: 2631
Epoch: 49, global_step=196608
SPS: 2648
Epoch: 50, global_step=200704
SPS: 2652
Epoch: 51, global_step=204800
Evaluating
2025-05-19 05:46:43,083 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
2025-05-19 05:46:49,363 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Backend tkagg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/workspace/ManiSkill/examples/baselines/ppo/ppo.py", line 283, in <module>
    eval_obs, eval_rew, eval_terminations, eval_truncations, eval_infos = eval_envs.step(agent.get_action(eval_obs, deterministic=True))
  File "/workspace/ManiSkill/mani_skill/vector/wrappers/gymnasium.py", line 148, in step
    obs, infos = self.reset(options=dict(env_idx=env_idx))
  File "/workspace/ManiSkill/mani_skill/vector/wrappers/gymnasium.py", line 93, in reset
    obs, info = self._env.reset(seed=seed, options=options)
  File "/workspace/ManiSkill/mani_skill/utils/wrappers/record.py", line 376, in reset
    obs, info = super().reset(*args, seed=seed, options=options, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/core.py", line 467, in reset
    return self.env.reset(seed=seed, options=options)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/core.py", line 467, in reset
    return self.env.reset(seed=seed, options=options)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/wrappers/order_enforcing.py", line 61, in reset
    return self.env.reset(**kwargs)
  File "/workspace/ManiSkill/mani_skill/envs/sapien_env.py", line 937, in reset
    info = self.get_info()
  File "/workspace/ManiSkill/mani_skill/envs/sapien_env.py", line 1118, in get_info
    info.update(self.evaluate())
  File "/workspace/ManiSkill/mani_skill/envs/tasks/quadruped/quadruped_reach.py", line 100, in evaluate
    is_fallen = self.agent.is_fallen()
  File "/workspace/ManiSkill/mani_skill/agents/robots/anymal/anymal_c.py", line 114, in is_fallen
    forces = self.robot.get_net_contact_forces(["base"])
  File "/workspace/ManiSkill/mani_skill/utils/structs/articulation.py", line 497, in get_net_contact_forces
    return self.get_net_contact_impulses(link_names) / self.scene.timestep
  File "/workspace/ManiSkill/mani_skill/utils/structs/articulation.py", line 456, in get_net_contact_impulses
    self.px.gpu_query_contact_body_impulses(query)
RuntimeError: CUDA error: out of memory
```

Both cases were ran with vscode's python debugger so I was able to check VRAM usage when OOM error is triggered and the VRAM usage is not  anywhere near the capacity:
```
|  0%   45C    P5              15W / 200W |   5249MiB / 12282MiB |      7%      Default |

```

Another behavior I have noticed is that the OOM error happens at the same evaluation epoch step given the same training args.

For example, when training with `AnymalC-Reach-v1` and 256 training envs. The #51 epoch will always fail at evaluation phase due to OOM. 

I also tried to decrease `num-eval-steps` from 200 to 16. With decreased number of steps, the training always fails at epoch 151 with following message and trackback:
```
(base) root@5a9cae070a1f:/workspace#  cd /workspace ; /usr/bin/env /opt/conda/bin/python /root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 52855 -- /workspace/ManiSkill/examples/baselines/ppo/ppo.py --env_id AnymalC-Reach-v1 --seed 1 --num_envs 256 --update_epochs 8 --num_minibatches 32 --gamma 0.99 --gae_lambda 0.95 --total_timesteps 50000000 --num-steps 16 --num-eval-steps 16 --num_eval_envs 16 --track 
2025-05-19 06:15:37,349 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
2025-05-19 06:15:37,952 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Saving eval videos to runs/AnymalC-Reach-v1__ppo__1__1747635335/videos
Running training
2025-05-19 06:15:40,967 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
####
args.num_iterations=12207 args.num_envs=256 args.num_eval_envs=16
args.minibatch_size=128 args.batch_size=4096 args.update_epochs=8
####
Epoch: 1, global_step=0
Evaluating
2025-05-19 06:15:41,363 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Evaluated 256 steps resulting in 0 episodes
model saved to runs/AnymalC-Reach-v1__ppo__1__1747635335/ckpt_1.pt
SPS: 1297
Epoch: 2, global_step=4096
SPS: 1938
Epoch: 3, global_step=8192
SPS: 2332
Epoch: 4, global_step=12288
SPS: 2588
Epoch: 5, global_step=16384
SPS: 2782
Epoch: 6, global_step=20480
SPS: 2908
Epoch: 7, global_step=24576
SPS: 3009
Epoch: 8, global_step=28672
SPS: 3113
Epoch: 9, global_step=32768
SPS: 3208
Epoch: 10, global_step=36864
SPS: 3285
Epoch: 11, global_step=40960
SPS: 3356
Epoch: 12, global_step=45056
SPS: 3404
Epoch: 13, global_step=49152
SPS: 3462
Epoch: 14, global_step=53248
SPS: 3514
Epoch: 15, global_step=57344
SPS: 3543
Epoch: 16, global_step=61440
SPS: 3563
Epoch: 17, global_step=65536
SPS: 3585
Epoch: 18, global_step=69632
SPS: 3612
Epoch: 19, global_step=73728
SPS: 3639
Epoch: 20, global_step=77824
SPS: 3623
Epoch: 21, global_step=81920
SPS: 3602
Epoch: 22, global_step=86016
SPS: 3617
Epoch: 23, global_step=90112
SPS: 3615
Epoch: 24, global_step=94208
SPS: 3608
Epoch: 25, global_step=98304
SPS: 3616
Epoch: 26, global_step=102400
Evaluating
2025-05-19 06:16:09,322 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Evaluated 256 steps resulting in 0 episodes
model saved to runs/AnymalC-Reach-v1__ppo__1__1747635335/ckpt_26.pt
SPS: 3507
Epoch: 27, global_step=106496
SPS: 3532
Epoch: 28, global_step=110592
SPS: 3546
Epoch: 29, global_step=114688
SPS: 3552
Epoch: 30, global_step=118784
SPS: 3565
Epoch: 31, global_step=122880
SPS: 3574
Epoch: 32, global_step=126976
SPS: 3596
Epoch: 33, global_step=131072
SPS: 3605
Epoch: 34, global_step=135168
SPS: 3619
Epoch: 35, global_step=139264
SPS: 3636
Epoch: 36, global_step=143360
SPS: 3646
Epoch: 37, global_step=147456
SPS: 3676
Epoch: 38, global_step=151552
SPS: 3689
Epoch: 39, global_step=155648
SPS: 3704
Epoch: 40, global_step=159744
SPS: 3710
Epoch: 41, global_step=163840
SPS: 3704
Epoch: 42, global_step=167936
SPS: 3693
Epoch: 43, global_step=172032
SPS: 3679
Epoch: 44, global_step=176128
SPS: 3664
Epoch: 45, global_step=180224
SPS: 3676
Epoch: 46, global_step=184320
SPS: 3669
Epoch: 47, global_step=188416
SPS: 3656
Epoch: 48, global_step=192512
SPS: 3654
Epoch: 49, global_step=196608
SPS: 3668
Epoch: 50, global_step=200704
SPS: 3677
Epoch: 51, global_step=204800
Evaluating
2025-05-19 06:16:36,798 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Evaluated 256 steps resulting in 0 episodes
model saved to runs/AnymalC-Reach-v1__ppo__1__1747635335/ckpt_51.pt
SPS: 3591
Epoch: 52, global_step=208896
SPS: 3592
Epoch: 53, global_step=212992
SPS: 3616
Epoch: 54, global_step=217088
SPS: 3640
Epoch: 55, global_step=221184
SPS: 3643
Epoch: 56, global_step=225280
SPS: 3641
Epoch: 57, global_step=229376
SPS: 3632
Epoch: 58, global_step=233472
SPS: 3660
Epoch: 59, global_step=237568
SPS: 3682
Epoch: 60, global_step=241664
SPS: 3713
Epoch: 61, global_step=245760
SPS: 3735
Epoch: 62, global_step=249856
SPS: 3765
Epoch: 63, global_step=253952
SPS: 3799
Epoch: 64, global_step=258048
SPS: 3780
Epoch: 65, global_step=262144
SPS: 3816
Epoch: 66, global_step=266240
SPS: 3820
Epoch: 67, global_step=270336
SPS: 3848
Epoch: 68, global_step=274432
SPS: 3877
Epoch: 69, global_step=278528
SPS: 3900
Epoch: 70, global_step=282624
SPS: 3929
Epoch: 71, global_step=286720
SPS: 3933
Epoch: 72, global_step=290816
SPS: 3923
Epoch: 73, global_step=294912
SPS: 3950
Epoch: 74, global_step=299008
SPS: 3985
Epoch: 75, global_step=303104
SPS: 4013
Epoch: 76, global_step=307200
Evaluating
2025-05-19 06:16:57,613 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Evaluated 256 steps resulting in 0 episodes
model saved to runs/AnymalC-Reach-v1__ppo__1__1747635335/ckpt_76.pt
SPS: 3972
Epoch: 77, global_step=311296
SPS: 3997
Epoch: 78, global_step=315392
SPS: 4003
Epoch: 79, global_step=319488
SPS: 4020
Epoch: 80, global_step=323584
SPS: 4035
Epoch: 81, global_step=327680
SPS: 4058
Epoch: 82, global_step=331776
SPS: 4083
Epoch: 83, global_step=335872
SPS: 4095
Epoch: 84, global_step=339968
SPS: 4113
Epoch: 85, global_step=344064
SPS: 4139
Epoch: 86, global_step=348160
SPS: 4164
Epoch: 87, global_step=352256
SPS: 4191
Epoch: 88, global_step=356352
SPS: 4220
Epoch: 89, global_step=360448
SPS: 4227
Epoch: 90, global_step=364544
SPS: 4254
Epoch: 91, global_step=368640
SPS: 4277
Epoch: 92, global_step=372736
SPS: 4293
Epoch: 93, global_step=376832
SPS: 4301
Epoch: 94, global_step=380928
SPS: 4328
Epoch: 95, global_step=385024
SPS: 4346
Epoch: 96, global_step=389120
SPS: 4358
Epoch: 97, global_step=393216
SPS: 4370
Epoch: 98, global_step=397312
SPS: 4378
Epoch: 99, global_step=401408
SPS: 4381
Epoch: 100, global_step=405504
SPS: 4393
Epoch: 101, global_step=409600
Evaluating
2025-05-19 06:17:14,279 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Evaluated 256 steps resulting in 0 episodes
model saved to runs/AnymalC-Reach-v1__ppo__1__1747635335/ckpt_101.pt
SPS: 4347
Epoch: 102, global_step=413696
SPS: 4349
Epoch: 103, global_step=417792
SPS: 4359
Epoch: 104, global_step=421888
SPS: 4373
Epoch: 105, global_step=425984
SPS: 4397
Epoch: 106, global_step=430080
SPS: 4408
Epoch: 107, global_step=434176
SPS: 4413
Epoch: 108, global_step=438272
SPS: 4435
Epoch: 109, global_step=442368
SPS: 4456
Epoch: 110, global_step=446464
SPS: 4468
Epoch: 111, global_step=450560
SPS: 4478
Epoch: 112, global_step=454656
SPS: 4492
Epoch: 113, global_step=458752
SPS: 4507
Epoch: 114, global_step=462848
SPS: 4523
Epoch: 115, global_step=466944
SPS: 4542
Epoch: 116, global_step=471040
SPS: 4551
Epoch: 117, global_step=475136
SPS: 4563
Epoch: 118, global_step=479232
SPS: 4581
Epoch: 119, global_step=483328
SPS: 4603
Epoch: 120, global_step=487424
SPS: 4623
Epoch: 121, global_step=491520
SPS: 4637
Epoch: 122, global_step=495616
SPS: 4657
Epoch: 123, global_step=499712
SPS: 4677
Epoch: 124, global_step=503808
SPS: 4698
Epoch: 125, global_step=507904
SPS: 4713
Epoch: 126, global_step=512000
Evaluating
2025-05-19 06:17:29,630 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Evaluated 256 steps resulting in 0 episodes
model saved to runs/AnymalC-Reach-v1__ppo__1__1747635335/ckpt_126.pt
SPS: 4685
Epoch: 127, global_step=516096
SPS: 4702
Epoch: 128, global_step=520192
SPS: 4715
Epoch: 129, global_step=524288
SPS: 4732
Epoch: 130, global_step=528384
SPS: 4748
Epoch: 131, global_step=532480
SPS: 4766
Epoch: 132, global_step=536576
SPS: 4786
Epoch: 133, global_step=540672
SPS: 4786
Epoch: 134, global_step=544768
SPS: 4790
Epoch: 135, global_step=548864
SPS: 4806
Epoch: 136, global_step=552960
SPS: 4820
Epoch: 137, global_step=557056
SPS: 4827
Epoch: 138, global_step=561152
SPS: 4838
Epoch: 139, global_step=565248
SPS: 4846
Epoch: 140, global_step=569344
SPS: 4861
Epoch: 141, global_step=573440
SPS: 4875
Epoch: 142, global_step=577536
SPS: 4889
Epoch: 143, global_step=581632
SPS: 4893
Epoch: 144, global_step=585728
SPS: 4903
Epoch: 145, global_step=589824
SPS: 4913
Epoch: 146, global_step=593920
SPS: 4931
Epoch: 147, global_step=598016
SPS: 4941
Epoch: 148, global_step=602112
SPS: 4953
Epoch: 149, global_step=606208
SPS: 4968
Epoch: 150, global_step=610304
SPS: 4972
Epoch: 151, global_step=614400
Evaluating
2025-05-19 06:17:44,655 - mani_skill  - WARNING - No initial pose set for actor builder of goal, setting to default pose q=[1,0,0,0], p=[0,0,0]. Not setting reasonable initial poses may slow down simulation, see https://github.com/haosulab/ManiSkill/issues/421.
Backend tkagg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/workspace/ManiSkill/examples/baselines/ppo/ppo.py", line 278, in <module>
    eval_obs, _ = eval_envs.reset()
  File "/workspace/ManiSkill/mani_skill/vector/wrappers/gymnasium.py", line 93, in reset
    obs, info = self._env.reset(seed=seed, options=options)
  File "/workspace/ManiSkill/mani_skill/utils/wrappers/record.py", line 376, in reset
    obs, info = super().reset(*args, seed=seed, options=options, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/core.py", line 467, in reset
    return self.env.reset(seed=seed, options=options)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/core.py", line 467, in reset
    return self.env.reset(seed=seed, options=options)
  File "/opt/conda/lib/python3.9/site-packages/gymnasium/wrappers/order_enforcing.py", line 61, in reset
    return self.env.reset(**kwargs)
  File "/workspace/ManiSkill/mani_skill/envs/sapien_env.py", line 937, in reset
    info = self.get_info()
  File "/workspace/ManiSkill/mani_skill/envs/sapien_env.py", line 1118, in get_info
    info.update(self.evaluate())
  File "/workspace/ManiSkill/mani_skill/envs/tasks/quadruped/quadruped_reach.py", line 100, in evaluate
    is_fallen = self.agent.is_fallen()
  File "/workspace/ManiSkill/mani_skill/agents/robots/anymal/anymal_c.py", line 114, in is_fallen
    forces = self.robot.get_net_contact_forces(["base"])
  File "/workspace/ManiSkill/mani_skill/utils/structs/articulation.py", line 497, in get_net_contact_forces
    return self.get_net_contact_impulses(link_names) / self.scene.timestep
  File "/workspace/ManiSkill/mani_skill/utils/structs/articulation.py", line 458, in get_net_contact_impulses
    query.cuda_impulses.torch()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2025-05-19 06:23:43.838] [SAPIEN] [critical] /buildAgent/work/eb2f45c4acc808a0/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp
[2025-05-19 06:23:43.838] [SAPIEN] [critical] Mem free failed with error code 700!

[2025-05-19 06:23:43.838] [SAPIEN] [critical] /buildAgent/work/eb2f45c4acc808a0/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp
[2025-05-19 06:23:43.838] [SAPIEN] [critical] /buildAgent/work/eb2f45c4acc808a0/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp
[2025-05-19 06:23:43.838] [SAPIEN] [critical] /buildAgent/work/eb2f45c4acc808a0/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp
[2025-05-19 06:23:43.838] [SAPIEN] [critical] /buildAgent/work/eb2f45c4acc808a0/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp
[2025-05-19 06:23:43.839] [SAPIEN] [critical] /buildAgent/work/eb2f45c4acc808a0/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp
CUDA error at /__w/SAPIEN/SAPIEN/3rd_party/sapien-vulkan-2/src/core/buffer.cpp 103: an illegal memory access was encountered
```

Here's a screenshot in vscode when OOM is triggered:

![Image](https://github.com/user-attachments/assets/2e98a912-f71a-4f2a-8cae-7fb4d68f8bcc)

This was tested on a RTX4070 and the driver versions are:
```
Driver Version: 535.230.02   CUDA Version: 12.2
```

I have also observed the same consistent CUDA error (OOM or illegal access) behavior on the aforementioned H100 machine (with 570 driver): running `ManiSkill/examples/baselines/ppo/ppo.py --env_id AnymalC-Reach-v1` and crashing at the same epoch when there's more than enough VRAM.

For now, I am going to run with evaluation disabled I guess.

**Comment by StoneT2000** [comment]
I wonder if this is an issue of using the contact force APIs and reconfiguration. I recall that the AnymalC-Reach-v1 environment would have this particular crash when `query.cuda_impulses.torch()` is called if the environment is reconfigured (which we only do by default for eval envs, originally because we want to ensure everything is randomized including object geometries if the task does randomize it).

Could you try turning reconfiguration frequency to 0 and try again?

**Comment by kwang-12** [comment]
Can confirm that modifying reconfiguration frequency to 0 makes the problem go away.
Is this a problem on the SAPIEN's side?

**Comment by StoneT2000** [comment]
It might be. Maybe some issue with memory not being reallocated for contact buffers once deleting the env, unsure.

For now just avoid reconfiguration (you probably don't need it anyway for the most part)

**Comment by jpizarrom** [comment]
Hi @StoneT2000,

I had the same OOM issue following https://github.com/StoneT2000/lerobot-sim2real, and also the OOM was solved with `--ppo.eval_reconfiguration_freq=0`

NVIDIA RTX  Laptop GPU 16GB
NVIDIA-SMI 550.67
Driver Version: 550.67
CUDA Version: 12.4

```
seed=3
python lerobot_sim2real/scripts/train_ppo_rgb.py --env-id="SO100GraspCube-v1" --env-kwargs-json-path=env_config.json \
  --ppo.seed=${seed} \
  --ppo.num_envs=1024 --ppo.num-steps=16 --ppo.update_epochs=8 --ppo.num_minibatches=32 \
  --ppo.total_timesteps=100_000_000 --ppo.gamma=0.9 \
  --ppo.num_eval_envs=16 --ppo.num-eval-steps=64 --ppo.no-partial-reset \
  --ppo.exp-name="ppo-SO100GraspCube-v1-rgb-${seed}" \
  --ppo.track --ppo.wandb_project_name "SO100-ManiSkill" \
  --ppo.eval_reconfiguration_freq=0
```

**Comment by StoneT2000** [comment]
I'm not sure where this jump is coming from still, I have yet to reproduce it for the lerobot sim2real environments.


Can you share with me the result of pip list? And what exact GPU are you using?

**Comment by jpizarrom** [comment]
This is my conda env https://gist.github.com/jpizarrom/afd31c4b6164bffc9e4444a19c7cb26d

NVIDIA-SMI 550.144.03
Driver Version: 550.144.03
CUDA Version: 12.4
NVIDIA RTX A5500 Laptop GPU

**Comment by paLeziart** [comment]
Hello @StoneT2000 

I also encountered this issue recently in a custom environment I made. I was getting an out-of-memory issue the fourth time the eval envs were called. Like with eval freq at 250 it would trigger at iteration 750. Reducing the eval freq did not change the pattern of triggering at the fourth evaluation.

The issue suddenly appeared so I managed to easily track it down to something I had added: a call to `env.agent.robot.get_net_contact_forces(["left_ankle_link"])` in my `_get_obs_state_dict` custom function. So instead I'm computing and storing the contact forces in a class attribute inside `_after_simulation_step`, that I later access without issue in `_get_obs_state_dict`.

I assume the out-of-memory issue comes from calling the contact API during the reset of all eval envs at the start of the evaluation process. I had the issue because `get_obs` is called at the end of `reset` in BaseEnv class. Switching the API call to `_after_simulation_step` dodges the issue because it is not called during reset.

Using:
Ubuntu 24.04
NVIDIA-SMI 570.133.07
Driver Version 570.133.07
CUDA Version: 12.8
NVIDIA RTX 4090

Note that my training uses around 10 Gb out of the 24 Gb of the card so there is quite a lot of free memory.

**Comment by jpizarrom** [comment]
in _after_reconfigure when rgb_overlay_mode="none", the self._objects_to_remove_from_greenscreen is not being empty, so all the refs are kept in the array

**Comment by StoneT2000** [comment]
Some progress on debugging from my side so far:

I tried running the AnymalC-Reach-v1 example and it seems that after multiple reconfigures I will get a illegal memory access error when trying to get the impulses/forces of the "base" link specifically. Several other links seem fine like the "RH_FOOT" one.

Still confusing to me why putting the force computation code to after the simulation reset obs generation process is fine. The only thing that happens in between is that you now take an environment step before generating the force data (the first reset obs will now be using old force data if you cache it)

**Comment by StoneT2000** [comment]
Ok @fbxiang and I have found the bug.

It turns out the net contact forces API has a bug when there is no contacts, a cuda kernel is launched incorrectly, eventually leading to some strange behavior like invalid memory reads.

I will tag this issue once the fix is released.

**Comment by StoneT2000** [comment]
closed by #1194 

install the latest maniskill nightly, should be fixed
